### PR TITLE
GSoC Application 2015[Chetna Gupta]: Crowdsourcing for Guyana Deaf Community 

### PR DESCRIPTION
**Pull request by cheatiiit**

### CODE REVIEW

**Comment by Neetuj** [comment]
Looks fine to me . they are just minor edits

**Comment by rosariorobinson** [comment]
This PR should be submitted against the project repo which is called "crowdmap". The link is below. Please resubmit against the crowdmap repo and going forward.

https://github.com/systers/crowdmap

**Comment by yaseppochi** [comment]
@cheatiiit @rosariorobinson Somebody should close this pull request....

**Comment by jproft** [comment]
Thanks, @yaseppochi. Closing now.

**Pull request closed without merging**
